### ISSUE TITLE
should I pre-process raw data I download from opennre? When I train nyt10, it occur keyerror

### ISSUE THREAD

**Issue by jxyxiangyu** [slczgwh/REDN#10]
```
Traceback (most recent call last):
  File "./redn_trainer.py", line 206, in <module>
    train(**args_list[0])
  File "./redn_trainer.py", line 93, in train
    train_loader, val_loader, test_loader = get_dataset(_model)
  File "./redn_trainer.py", line 63, in get_dataset
    dataset_file))
  File "./redn_trainer.py", line 62, in <lambda>
    sort=sort),
  File "/home/aistudio/REDN-master/opennre/framework/data_loader.py", line 37, in __init__
    self.load(sort, sort_reverse)
  File "/home/aistudio/REDN-master/opennre/framework/data_loader.py", line 63, in load
    _d["entity_list"] = [_d["h"], _d["t"]]
KeyError: 'h'
```

**Comment by slczgwh** [comment]
Please confirm your dataset is right. It seems no head entity's key in your files.
