### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by kemalaraz** [slczgwh/REDN#2]
In OpenNRE nyt10 files are txt files so I'm trying to find json files but so far no luck for the original ones however I found pre-processed nyt10 .json files but when I ran the code no matter what the data is I am getting that error. 

```
==========nyt10 None============
@@@@@@@@@@@ args @@@@@@@@@@@
{'metric': 'micro_f1', 'cuda_device': 3, 'seed': 31415926535897932, 'opt': 'adam', 'use_cls': True, 'subject_1': False, 'large_bert': False, 'continue_train': False, 'eval': False, 'add_subject_loss': False, 'weight_decay': 1e-05, 'lr': 5e-05, 'max_epoch': 100, 'sort': False, 'softmax': False, 'num_workers': 2, 'dataset_name': 'nyt10', 'batch_size': 20}
@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Traceback (most recent call last):
  File "redn_trainer.py", line 205, in <module>
    train(**args_list[0])
  File "redn_trainer.py", line 92, in train
    train_loader, val_loader, test_loader = get_dataset(_model)
  File "redn_trainer.py", line 62, in get_dataset
    sort=sort), dataset_file))
  File "redn_trainer.py", line 62, in <lambda>
    sort=sort), dataset_file))
  File "/home/karaz/Desktop/Relation_Extraction/Relation_Extraction_English/REDN/opennre/framework/data_loader.py", line 37, in __init__
    self.load(sort, sort_reverse)
  File "/home/karaz/Desktop/Relation_Extraction/Relation_Extraction_English/REDN/opennre/framework/data_loader.py", line 48, in load
    _d["token"] = _d["text"].split(" ")
TypeError: list indices must be integers or slices, not str
```

**Comment by slczgwh** [comment]
We have download this dataset by using [.sh](https://github.com/thunlp/OpenNRE/blob/master/benchmark/download_nyt10.sh) from OpenNRE. This file is .txt but its content is actually a json. You can simply change it to .json and try it again.

**Comment by kemalaraz** [comment]
After changing to .json error disappeared, thanks:)
